### PR TITLE
Respect no_prefix for Consul keys

### PR DESCRIPTION
**Pull request by freddygv**
Fixes: #190

Previously, the configuration option `no_prefix` was implemented for keys read from Vault but not from Consul.

This PR implements the behavior as stated in the [docs](https://github.com/hashicorp/envconsul/blob/master/README.md): 
> This [noprefix] tells Envconsul to not prefix the keys with their parent "folder".

### CODE REVIEW

**Comment by eikenb** [comment]
This changes the default behavior for Consul keys. Currently they default to having no prefix, as if no_prefix defaulted to true. This changes no_prefix's default to false, so that they would all have prefixes.

I'm afraid changing the default behavior will break existing uses.

Would it be possible to have it default to true?

**Comment by freddygv** [comment]
We could have `NoPrefix` default to true, but then we introduce a similar issue for Vault keys.

Right now they default to including the prefix when `no_prefix` isn't set.

Thoughts, @banks?

**Comment by banks** [comment]
I think inconsistency is not nice but it's better than breaking changes!

I'd vote for keeping Consul's default behaviour unchanged even if that
means this argument has a different default for Consul and Vault - ideally
we could call that out in docs (godoc and readme for now but I think later
we'll want something richer?)

I'd defer to John on that though. Great catch John!

**Comment by freddygv** [comment]
@eikenb I took a pass at allowing Consul and Vault to have different defaults for `NoPrefix`. This was done by not setting a default value when the config is initialized.

Now users who weren't setting that flag won't see a change in behavior.

**Pull request merged**
