### PR TITLE
Support multiple secret entries for same vault key

### PR DESCRIPTION
**Pull request by lawrencejones**
This commit changes the mapping of configPrefixMap to link back to many
PrefixConfig's, should more than one config share the same dependency.
It fixes an issue where secrets for the same vault value would have just
one be set non-deterministically.

As an example, valid envconsul config is:

```json
{
  "vault": {
    "address": "https://vault.io",
    "token": "<token>"
  },
  "exec": {
    "command": "some-command"
  },
  "secret": [
    {
      "format": "DB_USER",
      "path": "secret/data/app-db-user/2020010201"
    },
    {
      "format": "APP_DB_USER",
      "path": "secret/data/app-db-user/2020010201"
    }
  ]
}
```

Unfortunately, vault dependencies were linked back to their secret via a
map of vault dependency hash->secret. As each of these secrets had the
same hash, it was undefined behaviour as to which key would be set, as
it's dependent on the iteration order of Go maps.

An example of running this command once:

```
bash-4.3# echo $DB_USER
user_live
bash-4.3# echo $APP_DB_USER
secret/data/app-db-user/2020010201
```

Then again:

```
bash-4.3# echo $DB_USER
secret/data/app-db-user/2020010201
bash-4.3# echo $APP_DB_USER
user_live
```

With this change, running envconsul yields this every time:

```
bash-4.3# echo $DB_USER
user_live
bash-4.3# echo $APP_DB_USER
user_live
```

### CODE REVIEW

**Comment by lawrencejones** [comment]
I have no idea about my way round this codebase, so defer to the maintainers for some help figuring out if this is the best approach. It empirically solves the problem we found though, so at least that's a start!

**Comment by dekimsey** [comment]
So, I cannot tell if this is in the same vein as this issue, but it smells like it. So I'm commenting on this PR. In my case, envconsul is always overwriting previous keys, not flip-flopping as in the reported example. It seemed like duplicating secrets didn't work (and I have to be able to do :/). Though, I suspect it might be because I'm using the database mount and not the kv.2 mount in Vault for these secrets.

```
secret {
  format = "FOO.system.{{key}}"
  no_prefix = true
  path = "database/creds/thedb"
}
secret {
  format = "BAR.system.{{key}}"
  no_prefix = true
  path = "database/creds/thedb"
}
```

Results in the following behavior:
```
[DEBUG] Found KV2 secret
[DEBUG] (runner) setting BAR.system.password from vault.read(database/creds/thedb)
[DEBUG] (runner) setting BAR.system.username from vault.read(database/creds/thedb)
[DEBUG] (runner) overwriting BAR.system.username from vault.read(database/creds/thedb)
[DEBUG] (runner) overwriting BAR.system.password from vault.read(database/creds/thedb)
```

**Comment by eikenb** [comment]
Hey @lawrencejones, thanks for taking the time to submit this.

Just curious if you are still around and motivated to work on this?

**If not** I'll probably convert it to an issue and close the PR (linking to it from the bug for context and the possible bases for a fix). But **if you do** want to work on it some would you first please consider rebasing it on the master branch and resolving the conflicts. That would be a big help starting off. Thanks!

**Comment by lawrencejones** [comment]
Hey @eikenb, afraid I've since moved on and no longer use envconsul in my day job, so this wouldn't be something I'm well placed to work on. 

Tagging @benwh as the lead of my previous team. They might be interested in this if they still use envconsul, otherwise you're welcome to whatever works best for you with this PR.

**Comment by lawrencejones** [comment]
They're a great team, but may have moved on from this tool since I was around. Will tag @dyson as well, in case Ben is busy.

**Comment by eikenb** [comment]
Opened an issue for this going forward, #295.

**Pull request closed without merging**
