### PR TITLE
Fix kv2

### PR DESCRIPTION
**Pull request by noahhai**
Current kv2 fix in master is broken; only extracts the first key (randomly) from the data map. This is a fix.

### CODE REVIEW

**Comment by tyd** [comment]
Basically a dupe of https://github.com/hashicorp/envconsul/pull/192 

I've been using https://github.com/hashicorp/envconsul/pull/192 in production for several months. Any reason this approach is better/preferred?

**Comment by eikenb** [comment]
Hey @noahhai, thanks for the contribution.

I have a question about the included complex flag options. That is that they seem unrelated to KV2 support and I'm curious as to why are they included in this PR?

Thanks.

**Comment by noahhai** [comment]
@tyd  #192 only returns the first kvp from ["data"], so if you have ["data"] = {"A":1,"B":2}, it'll just return A=1
@eikenb it has my changes for PR #205. I'll remove them from this one..

**Comment by noahhai** [comment]
@tyd  sorry, this is a duplicate! was thinking #192 was for support of KV2. Closing this.

**Pull request closed without merging**
