### PR TITLE
Restore -timeout cli flag parsing

### PR DESCRIPTION
**Pull request by x-cray**

### CODE REVIEW

**Comment by x-cray** [comment]
@sethvargo Hi. Could you please help me figure out what's wrong with Travis build? Recently something has changed in HCL parsing library that makes such configs as `"totally not a valid config"` to be completely valid. To make things fail properly I've added exclamation marks to the end of line [here](https://github.com/x-cray/envconsul/commit/1c3896d32d04b9db5cbb2740573d7c4e20554ab7#diff-fb6a7899d06670e0e85669d2652ba911R262) and [here](https://github.com/x-cray/envconsul/commit/1c3896d32d04b9db5cbb2740573d7c4e20554ab7#diff-fb6a7899d06670e0e85669d2652ba911R543). But Travis build seems to run tests against wrong source files (those without exclamation marks) and fails these two cases. I tried to run `make updatedeps test testrace` on two different local environments and it worked great.

**Comment by sethvargo** [comment]
Hi @x-cray 

Yea, the HCL library changed. If you just revert that last commit, I can cherry pick and fix this up during triage. Don't worry about it :smile:

**Comment by x-cray** [comment]
Thanks. Removed the commit.

**Comment by arangamani** [comment]
@sethvargo any chance we could get this merged in?

**Comment by sethvargo** [comment]
e5328d7

**Pull request closed without merging**
